version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./laravel/:/var/www
        ports:
            - "${WEB_PORT}:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./laravel/:/var/www
        links:
            - database
            - cache
    database:
        image: mysql:5.6
        env_file:
            - database.env
        ports:
            - "${DATABASE_PORT}:3306"
    cache:
        image: redis:3.0
        ports:
            - "${CACHE_PORT}:6379"
